reminder feature ok
pauloborba/estacionamento pull request #4
Opened 2017-05-31 00:05 UTC by i27Allan

2017-06-05 14:05 UTC, pauloborba requested changes
isso é uma contribuição individual ou já é a integração da contribuição de Gabriel e Allan?

2017-06-05 14:05 UTC, pauloborba commented on grails-app/controllers/sistemadevagasdeestacionamento/VagaController.groovy
> +        vaga.reservas.last().setSaida(new Date())
deveria ser operação de Vaga

2017-06-05 14:05 UTC, pauloborba commented on grails-app/controllers/sistemadevagasdeestacionamento/VagaController.groovy
> +    }
anexa aqui no projeto o modelo de domínio

2017-06-05 14:05 UTC, pauloborba commented on grails-app/controllers/sistemadevagasdeestacionamento/VagaController.groovy
> +        reservasDoUsuario
retorna o que? não está fazendo sentido para mim.

2017-06-05 14:05 UTC, pauloborba commented on grails-app/controllers/sistemadevagasdeestacionamento/VagaController.groovy
> +            vaga.reservas.add(reserva)
deveria ser operação de Vaga

2017-06-05 14:05 UTC, pauloborba commented on test/cucumber/ParkingSpaceSignUp.feature
> +@ignore
por que os @ignore? não deveria enviar nada com @ignore

2017-06-05 14:05 UTC, pauloborba commented on test/cucumber/ReservaTrocaDeVaga.feature
> +@ignore
ver comentário anterior. ajustar espaçamento

2017-06-05 14:05 UTC, pauloborba commented on test/cucumber/steps/ParkingSpaceReminderSteps.groovy
> +//    controller.reminder(currentUser)
não entendi porque está comentado!

2017-06-05 14:05 UTC, pauloborba commented on test/cucumber/steps/ParkingSpaceReminderSteps.groovy
> +    ReservaTrocaDeVagaTestDataAndOperations.criarVaga(spot, sector, type)
não parece estar batendo com a semântica do passo

2017-06-05 14:05 UTC, pauloborba commented on test/cucumber/steps/ReservaTrocaDeVagaSteps.groovy
> +    page.reservarVaga(numero, setor, tipo)
reserva ou verifica se está reservada?

2017-06-05 14:05 UTC, pauloborba commented on test/cucumber/support/env.groovy
> +    User.list().each { it.delete(flush: true) }  */
por que comentou?

2017-06-05 14:05 UTC, pauloborba commented on test/functional/pages/HomePage.groovy
> +    def message(){ // quando o usuario não reservar e clicar no lembrete
renomear métodos

2017-06-08 00:10 UTC, i27Allan commented on test/cucumber/steps/ParkingSpaceReminderSteps.groovy
> +    ReservaTrocaDeVagaTestDataAndOperations.criarVaga(spot, sector, type)
ajustada

2017-06-08 00:25 UTC, i27Allan commented
Lembrete de Vaga ajustado.
Métodos renomeados e passo ajustado.

2017-06-13 19:28 UTC, pauloborba approved these changes

2017-06-13 19:28 UTC, pauloborba commented on grails-app/domain/sistemadevagasdeestacionamento/Vaga.groovy
> +        this.save(flush:true)
tirar save

2017-06-13 19:28 UTC, merged