Sugestão de Vaga
pauloborba/estacionamento pull request #6
Opened 2017-05-31 23:57 UTC by mlrbc

2017-06-05 14:19 UTC, pauloborba requested changes

2017-06-05 14:19 UTC, pauloborba commented on .gitignore
>  .classpath
ver comentários nos outros PRs. pelo que estou entendendo, só este era para ser revisado. os outros deveriam ter sido deletados então.

2017-06-05 14:19 UTC, pauloborba commented on grails-app/controllers/sistemadevagasdeestacionamento/UserController.groovy
> +            flash.message = "É sugerido a vaga ${vaga.getNumero()} do tipo ${vaga.getPreferenceType()} no setor ${vaga.getSetor()} para reserva"
pequena duplicação de código que pode ser facilmente evitada

2017-06-05 14:19 UTC, pauloborba commented on test/cucumber/steps/ParkingSpaceSignUpSteps.groovy
> +//
por que comentado?

2017-06-05 14:19 UTC, pauloborba commented on test/cucumber/steps/ReservaTrocaDeVagaSteps.groovy
> +//Given(~/^O sistema tem o usuario "([^"]*)" armazenado$/) { String username ->
ver comentário anterior

2017-06-05 14:19 UTC, pauloborba commented on test/cucumber/steps/SugestaoVagaSteps.groovy
> +    Vaga.sugestaoVaga(user)
deveria estar exercitando o controlador, já que o teste é de controlador

2017-06-05 14:19 UTC, pauloborba commented on test/cucumber/steps/SugestaoVagaSteps.groovy
> +    assert page.readFlashMessage() != null
melhor analisar o conteúdo da mensagem

2017-06-13 02:02 UTC, mlrbc commented on grails-app/controllers/sistemadevagasdeestacionamento/UserController.groovy
> +            flash.message = "É sugerido a vaga ${vaga.getNumero()} do tipo ${vaga.getPreferenceType()} no setor ${vaga.getSetor()} para reserva"
corrigido

2017-06-13 02:03 UTC, mlrbc commented on test/cucumber/steps/SugestaoVagaSteps.groovy
> +    Vaga.sugestaoVaga(user)
corrigido

2017-06-13 19:05 UTC, closed without merging